<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_GoogleAccountLogin
 */
?>
<?php /** @var \Amasty\GoogleAccountLogin\Block\LoginButton $block */ ?>
<?php $url = $block->getOneLoginUrl(); ?>
<?php if ($url) : ?>
    <div class="actions amgsuite-container">
        <a id='gsuite_button'
           title="<?= $block->escapeHtml(__('Sign in with Google')) ?>"
           class="amgsuite-button"
           href="<?= $block->escapeUrl($url) ?>"
        >
            <span class="amgsuite-text">
              <?= $block->escapeHtml(__('Sign in with Google')) ?>
            </span>
        </a>
    </div>
<?php endif; ?>
