<?php
/** @var $block \Magento\Backend\Block\Template */
$ajaxUrl = $block->getUrl('amasty_promoreports/reports/ajax');

/** @var $viewModel \Amasty\PromoReports\Model\ReportManagement */
$viewModel = $block->getViewModel();
$statisticFields = $viewModel->getStatisticFields();
?>
<div class="ampromo-report-container">
    <p class="ampromo-title">
        <?= $block->escapeHtml(__('Number of Active Free Gift Promo Campaigns as of Today: '))
        . $block->escapeHtml(__($viewModel->getCountActiveFreeGiftRules())) ?>
    </p>
</div>
<div class="ampromo-report-container">
    <div class="ampromo-report-statistic ampromo-block">
        <div class="ampromo-wrapper">
            <p class="ampromo-title">
                <?= $block->escapeHtml(__('Statistics')) ?>
            </p>
            <table class="ampromo-reports-table">
                <?php foreach ($statisticFields as $statisticKey => $statisticField): ?>
                    <tr class="ampromo-row">
                        <td class="ampromo-name col-name">
                            <?= $block->escapeHtml(__($statisticField)) ?>
                        </td>
                        <td class="ampromo-value" data-ampromo-js="<?= $block->escapeHtml(__($statisticKey)) ?>">-</td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div class="ampromo-report-chart ampromo-block">
        <div class="ampromo-wrapper">
            <div id="average-check-chart" class="ampromo-chart"></div>
        </div>
    </div>
</div>
<div class="ampromo-report-error message" data-ampromo-js="report-error"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "amasty_promo_reports": {
                "ajaxUrl": "<?= $block->escapeUrl($ajaxUrl) ?>",
                "chartContainerId" : "average-check-chart"
            }
        }
    }
</script>
